version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: always
    volumns:
      - mongodata:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 15s
      retries: 3
    ports:
      - "6379:6379"

  api:
    depends_on:
      - redis
    build:
      context: ./
    environment:
      REDIS_URL: redis:6379
      ADDR: :3001
    ports:
      - "3001:3001"
