package vimoptions

var Longs = map[string]int{
	"aleph":           1,
	"allowrevins":     2,
	"altkeymap":       3,
	"ambiwidth":       4,
	"antialias":       5,
	"autochdir":       6,
	"arabic":          7,
	"arabicshape":     8,
	"autoindent":      9,
	"autoread":        10,
	"autowrite":       11,
	"autowriteall":    12,
	"background":      13,
	"backspace":       14,
	"backup":          15,
	"backupcopy":      16,
	"backupdir":       17,
	"backupext":       18,
	"backupskip":      19,
	"balloondelay":    20,
	"ballooneval":     21,
	"balloonexpr":     22,
	"binary":          23,
	"bioskey":         24,
	"bomb":            25,
	"breakat":         26,
	"browsedir":       27,
	"bufhidden":       28,
	"buflisted":       29,
	"buftype":         30,
	"casemap":         31,
	"cdpath":          32,
	"cedit":           33,
	"charconvert":     34,
	"cindent":         35,
	"cinkeys":         36,
	"cinoptions":      37,
	"cinwords":        38,
	"clipboard":       39,
	"cmdheight":       40,
	"cmdwinheight":    41,
	"colorcolumn":     42,
	"columns":         43,
	"comments":        44,
	"commentstring":   45,
	"compatible":      46,
	"complete":        47,
	"completefunc":    48,
	"completeopt":     49,
	"concealcursor":   50,
	"conceallevel":    51,
	"confirm":         52,
	"conskey":         53,
	"copyindent":      54,
	"cpoptions":       55,
	"cryptmethod":     56,
	"cscopepathcomp":  57,
	"cscopeprg":       58,
	"cscopequickfix":  59,
	"cscopetag":       60,
	"cscopetagorder":  61,
	"cscopeverbose":   62,
	"cursorbind":      63,
	"cursorcolumn":    64,
	"cursorline":      65,
	"debug":           66,
	"define":          67,
	"delcombine":      68,
	"dictionary":      69,
	"diff":            70,
	"diffexpr":        71,
	"diffopt":         72,
	"digraph":         73,
	"directory":       74,
	"display":         75,
	"eadirection":     76,
	"edcompatible":    77,
	"encoding":        78,
	"endofline":       79,
	"equalalways":     80,
	"equalprg":        81,
	"errorbells":      82,
	"errorfile":       83,
	"errorformat":     84,
	"esckeys":         85,
	"eventignore":     86,
	"expandtab":       87,
	"exrc":            88,
	"fileencoding":    89,
	"fileencodings":   90,
	"fileformat":      91,
	"fileformats":     92,
	"filetype":        93,
	"fillchars":       94,
	"fkmap":           95,
	"foldclose":       96,
	"foldcolumn":      97,
	"foldenable":      98,
	"foldexpr":        99,
	"foldignore":      100,
	"foldlevel":       101,
	"foldlevelstart":  102,
	"foldmarker":      103,
	"foldmethod":      104,
	"foldminlines":    105,
	"foldnestmax":     106,
	"foldopen":        107,
	"foldtext":        108,
	"formatlistpat":   109,
	"formatoptions":   110,
	"formatprg":       111,
	"formatexpr":      112,
	"fsync":           113,
	"gdefault":        114,
	"grepformat":      115,
	"grepprg":         116,
	"guicursor":       117,
	"guifont":         118,
	"guifontset":      119,
	"guifontwide":     120,
	"guiheadroom":     121,
	"guioptions":      122,
	"guipty":          123,
	"guitablabel":     124,
	"guitabtooltip":   125,
	"helpfile":        126,
	"helpheight":      127,
	"helplang":        128,
	"hidden":          129,
	"highlight":       130,
	"hlsearch":        131,
	"history":         132,
	"hkmap":           133,
	"hkmapp":          134,
	"icon":            135,
	"iconstring":      136,
	"ignorecase":      137,
	"imactivatekey":   138,
	"imcmdline":       139,
	"imdisable":       140,
	"iminsert":        141,
	"imsearch":        142,
	"include":         143,
	"includeexpr":     144,
	"incsearch":       145,
	"indentexpr":      146,
	"indentkeys":      147,
	"infercase":       148,
	"insertmode":      149,
	"isfname":         150,
	"isident":         151,
	"iskeyword":       152,
	"isprint":         153,
	"joinspaces":      154,
	"key":             155,
	"keymap":          156,
	"keymodel":        157,
	"keywordprg":      158,
	"langmap":         159,
	"langmenu":        160,
	"laststatus":      161,
	"lazyredraw":      162,
	"linebreak":       163,
	"lines":           164,
	"linespace":       165,
	"lisp":            166,
	"lispwords":       167,
	"list":            168,
	"listchars":       169,
	"loadplugins":     170,
	"macatsui":        171,
	"magic":           172,
	"makeef":          173,
	"makeprg":         174,
	"matchpairs":      175,
	"matchtime":       176,
	"maxcombine":      177,
	"maxfuncdepth":    178,
	"maxmapdepth":     179,
	"maxmem":          180,
	"maxmempattern":   181,
	"maxmemtot":       182,
	"menuitems":       183,
	"mkspellmem":      184,
	"modeline":        185,
	"modelines":       186,
	"modifiable":      187,
	"modified":        188,
	"more":            189,
	"mouse":           190,
	"mousefocus":      191,
	"mousehide":       192,
	"mousemodel":      193,
	"mouseshape":      194,
	"mousetime":       195,
	"mzquantum":       196,
	"nrformats":       197,
	"number":          198,
	"numberwidth":     199,
	"omnifunc":        200,
	"opendevice":      201,
	"operatorfunc":    202,
	"osfiletype":      203,
	"paragraphs":      204,
	"paste":           205,
	"pastetoggle":     206,
	"patchexpr":       207,
	"patchmode":       208,
	"path":            209,
	"preserveindent":  210,
	"previewheight":   211,
	"previewwindow":   212,
	"printdevice":     213,
	"printencoding":   214,
	"printexpr":       215,
	"printfont":       216,
	"printheader":     217,
	"printmbcharset":  218,
	"printmbfont":     219,
	"printoptions":    220,
	"pumheight":       221,
	"quoteescape":     222,
	"readonly":        223,
	"redrawtime":      224,
	"relativenumber":  225,
	"remap":           226,
	"report":          227,
	"restorescreen":   228,
	"revins":          229,
	"rightleft":       230,
	"rightleftcmd":    231,
	"ruler":           232,
	"rulerformat":     233,
	"runtimepath":     234,
	"scroll":          235,
	"scrollbind":      236,
	"scrolljump":      237,
	"scrolloff":       238,
	"scrollopt":       239,
	"sections":        240,
	"secure":          241,
	"selection":       242,
	"selectmode":      243,
	"sessionoptions":  244,
	"shell":           245,
	"shellcmdflag":    246,
	"shellpipe":       247,
	"shellquote":      248,
	"shellredir":      249,
	"shellslash":      250,
	"shelltemp":       251,
	"shelltype":       252,
	"shellxquote":     253,
	"shiftround":      254,
	"shiftwidth":      255,
	"shortmess":       256,
	"shortname":       257,
	"showbreak":       258,
	"showcmd":         259,
	"showfulltag":     260,
	"showmatch":       261,
	"showmode":        262,
	"showtabline":     263,
	"sidescroll":      264,
	"sidescrolloff":   265,
	"smartcase":       266,
	"smartindent":     267,
	"smarttab":        268,
	"softtabstop":     269,
	"spell":           270,
	"spellcapcheck":   271,
	"spellfile":       272,
	"spelllang":       273,
	"spellsuggest":    274,
	"splitbelow":      275,
	"splitright":      276,
	"startofline":     277,
	"statusline":      278,
	"suffixes":        279,
	"suffixesadd":     280,
	"swapfile":        281,
	"swapsync":        282,
	"switchbuf":       283,
	"synmaxcol":       284,
	"syntax":          285,
	"tabstop":         286,
	"tabline":         287,
	"tabpagemax":      288,
	"tagbsearch":      289,
	"taglength":       290,
	"tagrelative":     291,
	"tags":            292,
	"tagstack":        293,
	"term":            294,
	"termbidi":        295,
	"termencoding":    296,
	"terse":           297,
	"textauto":        298,
	"textmode":        299,
	"textwidth":       300,
	"thesaurus":       301,
	"tildeop":         302,
	"timeout":         303,
	"timeoutlen":      304,
	"title":           305,
	"titlelen":        306,
	"titleold":        307,
	"titlestring":     308,
	"toolbar":         309,
	"toolbariconsize": 310,
	"ttimeout":        311,
	"ttimeoutlen":     312,
	"ttybuiltin":      313,
	"ttyfast":         314,
	"ttymouse":        315,
	"ttyscroll":       316,
	"ttytype":         317,
	"undodir":         318,
	"undofile":        319,
	"undolevels":      320,
	"undoreload":      321,
	"updatecount":     322,
	"updatetime":      323,
	"verbose":         324,
	"verbosefile":     325,
	"viewdir":         326,
	"viewoptions":     327,
	"viminfo":         328,
	"virtualedit":     329,
	"visualbell":      330,
	"warn":            331,
	"weirdinvert":     332,
	"whichwrap":       333,
	"wildchar":        334,
	"wildcharm":       335,
	"wildignore":      336,
	"wildignorecase":  337,
	"wildmenu":        338,
	"wildmode":        339,
	"wildoptions":     340,
	"winaltkeys":      341,
	"window":          342,
	"winheight":       343,
	"winfixheight":    344,
	"winfixwidth":     345,
	"winminheight":    346,
	"winminwidth":     347,
	"winwidth":        348,
	"wrap":            349,
	"wrapmargin":      350,
	"wrapscan":        351,
	"write":           352,
	"writeany":        353,
	"writebackup":     354,
	"writedelay":      355,
}

var Shorts = map[string]int{
	"al":      1,
	"ari":     2,
	"akm":     3,
	"ambw":    4,
	"anti":    5,
	"acd":     6,
	"arab":    7,
	"arshape": 8,
	"ai":      9,
	"ar":      10,
	"aw":      11,
	"awa":     12,
	"bg":      13,
	"bs":      14,
	"bk":      15,
	"bkc":     16,
	"bdir":    17,
	"bex":     18,
	"bsk":     19,
	"bdlay":   20,
	"beval":   21,
	"bexpr":   22,
	"bin":     23,
	"biosk":   24,
	"brk":     26,
	"bsdir":   27,
	"bh":      28,
	"bl":      29,
	"bt":      30,
	"cmp":     31,
	"cd":      32,
	"ccv":     34,
	"cin":     35,
	"cink":    36,
	"cino":    37,
	"cinw":    38,
	"cb":      39,
	"ch":      40,
	"cwh":     41,
	"cc":      42,
	"co":      43,
	"com":     44,
	"cms":     45,
	"cp":      46,
	"cpt":     47,
	"cfu":     48,
	"cot":     49,
	"cocu":    50,
	"cole":    51,
	"cf":      52,
	"consk":   53,
	"ci":      54,
	"cpo":     55,
	"cm":      56,
	"cspc":    57,
	"csprg":   58,
	"csqf":    59,
	"cst":     60,
	"csto":    61,
	"csverb":  62,
	"crb":     63,
	"cuc":     64,
	"cul":     65,
	"def":     67,
	"deco":    68,
	"dict":    69,
	"dex":     71,
	"dip":     72,
	"dg":      73,
	"dir":     74,
	"dy":      75,
	"ead":     76,
	"ed":      77,
	"enc":     78,
	"eol":     79,
	"ea":      80,
	"ep":      81,
	"eb":      82,
	"ef":      83,
	"efm":     84,
	"ek":      85,
	"ei":      86,
	"et":      87,
	"ex":      88,
	"fenc":    89,
	"fencs":   90,
	"ff":      91,
	"ffs":     92,
	"ft":      93,
	"fcs":     94,
	"fk":      95,
	"fcl":     96,
	"fdc":     97,
	"fen":     98,
	"fde":     99,
	"fdi":     100,
	"fdl":     101,
	"fdls":    102,
	"fmr":     103,
	"fdm":     104,
	"fml":     105,
	"fdn":     106,
	"fdo":     107,
	"fdt":     108,
	"flp":     109,
	"fo":      110,
	"fp":      111,
	"fex":     112,
	"fs":      113,
	"gd":      114,
	"gfm":     115,
	"gp":      116,
	"gcr":     117,
	"gfn":     118,
	"gfs":     119,
	"gfw":     120,
	"ghr":     121,
	"go":      122,
	"gtl":     124,
	"gtt":     125,
	"hf":      126,
	"hh":      127,
	"hlg":     128,
	"hid":     129,
	"hl":      130,
	"hls":     131,
	"hi":      132,
	"hk":      133,
	"hkp":     134,
	"ic":      137,
	"imak":    138,
	"imc":     139,
	"imd":     140,
	"imi":     141,
	"ims":     142,
	"inc":     143,
	"inex":    144,
	"is":      145,
	"inde":    146,
	"indk":    147,
	"inf":     148,
	"im":      149,
	"isf":     150,
	"isi":     151,
	"isk":     152,
	"isp":     153,
	"js":      154,
	"kmp":     156,
	"km":      157,
	"kp":      158,
	"lmap":    159,
	"lm":      160,
	"ls":      161,
	"lz":      162,
	"lbr":     163,
	"lsp":     165,
	"lw":      167,
	"lcs":     169,
	"lpl":     170,
	"mef":     173,
	"mp":      174,
	"mps":     175,
	"mat":     176,
	"mco":     177,
	"mfd":     178,
	"mmd":     179,
	"mm":      180,
	"mmp":     181,
	"mmt":     182,
	"mis":     183,
	"msm":     184,
	"ml":      185,
	"mls":     186,
	"ma":      187,
	"mod":     188,
	"mousef":  191,
	"mh":      192,
	"mousem":  193,
	"mouses":  194,
	"mouset":  195,
	"mzq":     196,
	"nf":      197,
	"nu":      198,
	"nuw":     199,
	"ofu":     200,
	"odev":    201,
	"opfunc":  202,
	"oft":     203,
	"para":    204,
	"pt":      206,
	"pex":     207,
	"pm":      208,
	"pa":      209,
	"pi":      210,
	"pvh":     211,
	"pvw":     212,
	"pdev":    213,
	"penc":    214,
	"pexpr":   215,
	"pfn":     216,
	"pheader": 217,
	"pmbcs":   218,
	"pmbfn":   219,
	"popt":    220,
	"ph":      221,
	"qe":      222,
	"ro":      223,
	"rdt":     224,
	"rnu":     225,
	"rs":      228,
	"ri":      229,
	"rl":      230,
	"rlc":     231,
	"ru":      232,
	"ruf":     233,
	"rtp":     234,
	"scr":     235,
	"scb":     236,
	"sj":      237,
	"so":      238,
	"sbo":     239,
	"sect":    240,
	"sel":     242,
	"slm":     243,
	"ssop":    244,
	"sh":      245,
	"shcf":    246,
	"sp":      247,
	"shq":     248,
	"srr":     249,
	"ssl":     250,
	"stmp":    251,
	"st":      252,
	"sxq":     253,
	"sr":      254,
	"sw":      255,
	"shm":     256,
	"sn":      257,
	"sbr":     258,
	"sc":      259,
	"sft":     260,
	"sm":      261,
	"smd":     262,
	"stal":    263,
	"ss":      264,
	"siso":    265,
	"scs":     266,
	"si":      267,
	"sta":     268,
	"sts":     269,
	"spc":     271,
	"spf":     272,
	"spl":     273,
	"sps":     274,
	"sb":      275,
	"spr":     276,
	"sol":     277,
	"stl":     278,
	"su":      279,
	"sua":     280,
	"swf":     281,
	"sws":     282,
	"swb":     283,
	"smc":     284,
	"syn":     285,
	"ts":      286,
	"tal":     287,
	"tpm":     288,
	"tbs":     289,
	"tl":      290,
	"tr":      291,
	"tag":     292,
	"tgst":    293,
	"tbidi":   295,
	"tenc":    296,
	"ta":      298,
	"tx":      299,
	"tw":      300,
	"tsr":     301,
	"top":     302,
	"to":      303,
	"tm":      304,
	"tb":      309,
	"tbis":    310,
	"ttm":     312,
	"tbi":     313,
	"tf":      314,
	"ttym":    315,
	"tsl":     316,
	"tty":     317,
	"udir":    318,
	"udf":     319,
	"ul":      320,
	"ur":      321,
	"uc":      322,
	"ut":      323,
	"vbs":     324,
	"vfile":   325,
	"vdir":    326,
	"vop":     327,
	"vi":      328,
	"ve":      329,
	"vb":      330,
	"wiv":     332,
	"ww":      333,
	"wc":      334,
	"wcm":     335,
	"wig":     336,
	"wic":     337,
	"wmnu":    338,
	"wim":     339,
	"wop":     340,
	"wak":     341,
	"wi":      342,
	"wh":      343,
	"wfh":     344,
	"wfw":     345,
	"wmh":     346,
	"wmw":     347,
	"wiw":     348,
	"wm":      350,
	"ws":      351,
	"wa":      353,
	"wb":      354,
	"wd":      355,
}

var Descriptions = []string{
	"ASCII code of the letter Aleph (Hebrew)",
	"allow CTRL-_ in Insert and Command-line mode",
	"for default second language (Farsi/Hebrew)",
	"what to do with Unicode chars of ambiguous width",
	"Mac OS X: use smooth, antialiased fonts",
	"change directory to the file in the current window",
	"for Arabic as a default second language",
	"do shaping for Arabic characters",
	"take indent for new line from previous line",
	"autom. read file when changed outside of Vim",
	"automatically write file if changed",
	"as 'autowrite', but works with more commands",
	"'dark' or 'light', used for highlight colors",
	"how backspace works at start of line",
	"keep backup file after overwriting a file",
	"make backup as a copy, don't rename the file",
	"list of directories for the backup file",
	"extension used for the backup file",
	"no backup for files that match these patterns",
	"delay in mS before a balloon may pop up",
	"switch on balloon evaluation",
	"expression to show in balloon",
	"read/write/edit file in binary mode",
	"MS-DOS: use bios calls for input characters",
	"prepend a Byte Order Mark to the file",
	"characters that may cause a line break",
	"which directory to start browsing in",
	"what to do when buffer is no longer in window",
	"whether the buffer shows up in the buffer list",
	"special type of buffer",
	"specifies how case of letters is changed",
	"list of directories searched with ':cd'",
	"key used to open the command-line window",
	"expression for character encoding conversion",
	"do C program indenting",
	"keys that trigger indent when 'cindent",
	"how to do indenting when 'cindent",
	"words where 'si",
	"use the clipboard as the unnamed register",
	"number of lines to use for the command-line",
	"height of the command-line window",
	"columns to highlight",
	"number of columns in the display",
	"patterns that can start a comment line",
	"template for comments; used for fold marker",
	"behave Vi-compatible as much as possible",
	"specify how Insert mode completion works",
	"function to be used for Insert mode completion",
	"options for Insert mode completion",
	"whether concealable text is hidden in cursor line",
	"whether concealable text is shown or hidden ",
	"ask what to do about unsaved/read-only files",
	"get keys directly from console (MS-DOS only)",
	"make 'autoindent",
	"flags for Vi-compatible behavior",
	"type of encryption to use for file writing",
	"how many components of the path to show",
	"command to execute cscope",
	"use quickfix window for cscope results",
	"use cscope for tag commands",
	"determines ':cstag' search order",
	"give messages when adding a cscope database",
	"move cursor in window as it moves in other windows",
	"highlight the screen column of the cursor",
	"highlight the screen line of the cursor",
	"set to 'msg' to see all error messages",
	"pattern to be used to find a macro definition",
	"delete combining characters on their own",
	"list of file names used for keyword completion",
	"use diff mode for the current window",
	"expression used to obtain a diff file",
	"options for using diff mode",
	"enable the entering of digraphs in Insert mode",
	"list of directory names for the swap file",
	"list of flags for how to display text",
	"in which direction 'equalalways",
	"toggle flags of ':substitute' command",
	"encoding used internally",
	"write <EOL> for last line in file",
	"windows are automatically made the same size",
	"external program to use for '=' command",
	"ring the bell for error messages",
	"name of the errorfile for the QuickFix mode",
	"description of the lines in the error file",
	"recognize function keys in Insert mode",
	"autocommand events that are ignored",
	"use spaces when <Tab> is inserted",
	"read .vimrc and .exrc in the current directory",
	"file encoding for multi-byte text",
	"automatically detected character encodings",
	"file format used for file I/O",
	"automatically detected values for 'fileformat'",
	"type of file, used for autocommands",
	"characters to use for displaying special items",
	"Farsi keyboard mapping",
	"close a fold when the cursor leaves it",
	"width of the column used to indicate folds",
	"set to display all folds open",
	"expression used when 'foldmethod",
	"ignore lines when 'foldmethod",
	"close folds with a level higher than this",
	"'foldlevel",
	"markers used when 'foldmethod",
	"folding type",
	"minimum number of lines for a fold to be closed",
	"maximum fold depth",
	"for which commands a fold will be opened",
	"expression used to display for a closed fold",
	"pattern used to recognize a list header",
	"how automatic formatting is to be done",
	"name of external program used with 'gq' command",
	"expression used with 'gq' command",
	"whether to invoke fsync() after file write",
	"the ':substitute' flag 'g",
	"format of 'grepprg",
	"program to use for ':grep'",
	"GUI: settings for cursor shape and blinking",
	"GUI: Name(s) of font(s) to be used",
	"GUI: Names of multi-byte fonts to be used",
	"list of font names for double-wide characters",
	"GUI: pixels room for window decorations",
	"GUI: Which components and options are used",
	"GUI: try to use a pseudo-tty for ':!' commands",
	"GUI: custom label for a tab page",
	"GUI: custom tooltip for a tab page",
	"full path name of the main help file",
	"minimum height of a new help window",
	"preferred help languages",
	"don't unload buffer when it is YXXYabandon|ed",
	"sets highlighting mode for various occasions",
	"highlight matches with last search pattern",
	"number of command-lines that are remembered",
	"Hebrew keyboard mapping",
	"phonetic Hebrew keyboard mapping",
	"let Vim set the text of the window icon",
	"string to use for the Vim icon text",
	"ignore case in search patterns",
	"key that activates the X input method",
	"use IM when starting to edit a command line",
	"do not use the IM in any mode",
	"use :lmap or IM in Insert mode",
	"use :lmap or IM when typing a search pattern",
	"pattern to be used to find an include file",
	"expression used to process an include line",
	"highlight match while typing search pattern",
	"expression used to obtain the indent of a line",
	"keys that trigger indenting with 'indentexpr'",
	"adjust case of match for keyword completion",
	"start the edit of a file in Insert mode",
	"characters included in file names and pathnames",
	"characters included in identifiers",
	"characters included in keywords",
	"printable characters",
	"two spaces after a period with a join command",
	"encryption key",
	"name of a keyboard mapping",
	"enable starting/stopping selection with keys",
	"program to use for the 'K' command",
	"alphabetic characters for other language mode",
	"language to be used for the menus",
	"tells when last window has status lines",
	"don't redraw while executing macros",
	"wrap long lines at a blank",
	"number of lines in the display",
	"number of pixel lines to use between characters",
	"automatic indenting for Lisp",
	"words that change how lisp indenting works",
	"show <Tab> and <EOL>",
	"characters for displaying in list mode",
	"load plugin scripts when starting up",
	"Mac GUI: use ATSUI text drawing",
	"changes special characters in search patterns",
	"name of the errorfile for ':make'",
	"program to use for the ':make' command",
	"pairs of characters that '%' can match",
	"tenths of a second to show matching paren",
	"maximum nr of combining characters displayed",
	"maximum recursive depth for user functions",
	"maximum recursive depth for mapping",
	"maximum memory (in Kbyte) used for one buffer",
	"maximum memory (in Kbyte) used for pattern search",
	"maximum memory (in Kbyte) used for all buffers",
	"maximum number of items in a menu",
	"memory used before |:mkspell| compresses the tree",
	"recognize modelines at start or end of file",
	"number of lines checked for modelines",
	"changes to the text are not possible",
	"buffer has been modified",
	"pause listings when the whole screen is filled",
	"enable the use of mouse clicks",
	"keyboard focus follows the mouse",
	"hide mouse pointer while typing",
	"changes meaning of mouse buttons",
	"shape of the mouse pointer in different modes",
	"max time between mouse double-click",
	"the interval between polls for MzScheme threads",
	"number formats recognized for CTRL-A command",
	"print the line number in front of each line",
	"number of columns used for the line number",
	"function for filetype-specific completion",
	"allow reading/writing devices on MS-Windows",
	"function to be called for |g@| operator",
	"operating system-specific filetype information",
	"nroff macros that separate paragraphs",
	"allow pasting text",
	"key code that causes 'paste",
	"expression used to patch a file",
	"keep the oldest version of a file",
	"list of directories searched with 'gf' et.al.",
	"preserve the indent structure when reindenting",
	"height of the preview window",
	"identifies the preview window",
	"name of the printer to be used for :hardcopy",
	"encoding to be used for printing",
	"expression used to print PostScript for :hardcopy",
	"name of the font to be used for :hardcopy",
	"format of the header used for :hardcopy",
	"CJK character set to be used for :hardcopy",
	"font names to be used for CJK output of :hardcopy",
	"controls the format of :hardcopy output",
	"maximum height of the popup menu",
	"escape characters used in a string",
	"disallow writing the buffer",
	"timeout for 'hlsearch",
	"show relative line number in front of each line",
	"allow mappings to work recursively",
	"threshold for reporting nr. of lines changed",
	"Win32: restore screen when exiting",
	"inserting characters will work backwards",
	"window is right-to-left oriented",
	"commands for which editing works right-to-left",
	"show cursor line and column in the status line",
	"custom format for the ruler",
	"list of directories used for runtime files",
	"lines to scroll with CTRL-U and CTRL-D",
	"scroll in window as other windows scroll",
	"minimum number of lines to scroll",
	"minimum nr. of lines above and below cursor",
	"how 'scrollbind",
	"nroff macros that separate sections",
	"secure mode for reading .vimrc in current dir",
	"what type of selection to use",
	"when to use Select mode instead of Visual mode",
	"options for |:mksession|",
	"name of shell to use for external commands",
	"flag to shell to execute one command",
	"string to put output of ':make' in error file",
	"quote character(s) for around shell command",
	"string to put output of filter in a temp file",
	"use forward slash for shell file names",
	"whether to use a temp file for shell commands",
	"Amiga: influences how to use a shell",
	"like 'shellquote', but include redirection",
	"round indent to multiple of shiftwidth",
	"number of spaces to use for (auto)indent step",
	"list of flags, reduce length of messages",
	"non-MS-DOS: Filenames assumed to be 8.3 chars",
	"string to use at the start of wrapped lines",
	"show (partial) command in status line",
	"show full tag pattern when completing tag",
	"briefly jump to matching bracket if insert one",
	"message on status line to show current mode",
	"tells when the tab pages line is displayed",
	"minimum number of columns to scroll horizontal",
	"min. nr. of columns to left and right of cursor",
	"no ignore case when pattern has uppercase",
	"smart autoindenting for C programs",
	"use 'shiftwidth",
	"number of spaces that <Tab> uses while editing",
	"enable spell checking",
	"pattern to locate end of a sentence",
	"files where |zg| and |zw| store words",
	"language(s) to do spell checking for",
	"method(s) used to suggest spelling corrections",
	"new window from split is below the current one",
	"new window is put right of the current one",
	"commands move cursor to first non-blank in line",
	"custom format for the status line",
	"suffixes that are ignored with multiple match",
	"suffixes added when searching for a file",
	"whether to use a swapfile for a buffer",
	"how to sync the swap file",
	"sets behavior when switching to another buffer",
	"maximum column to find syntax items",
	"syntax to be loaded for current buffer",
	"number of spaces that <Tab> in file uses",
	"custom format for the console tab pages line",
	"maximum number of tab pages for |-p| and 'tab all'",
	"use binary searching in tags files",
	"number of significant characters for a tag",
	"file names in tag file are relative",
	"list of file names used by the tag command",
	"push tags onto the tag stack",
	"name of the terminal",
	"terminal takes care of bi-directionality",
	"character encoding used by the terminal",
	"shorten some messages",
	"obsolete, use 'fileformats'",
	"obsolete, use 'fileformat'",
	"maximum width of text that is being inserted",
	"list of thesaurus files for keyword completion",
	"tilde command '~' behaves like an operator",
	"time out on mappings and key codes",
	"time out time in milliseconds",
	"let Vim set the title of the window",
	"percentage of 'columns' used for window title",
	"old title, restored when exiting",
	"string to use for the Vim window title",
	"GUI: which items to show in the toolbar",
	"size of the toolbar icons (for GTK 2 only)",
	"time out on mappings",
	"time out time for key codes in milliseconds",
	"use built-in termcap before external termcap",
	"indicates a fast terminal connection",
	"type of mouse codes generated",
	"maximum number of lines for a scroll",
	"alias for 'term'",
	"where to store undo files",
	"save undo information in a file",
	"maximum number of changes that can be undone",
	"max nr of lines to save for undo on a buffer reload",
	"after this many characters flush swap file",
	"after this many milliseconds flush swap file",
	"give informative messages",
	"file to write messages in",
	"directory where to store files with :mkview",
	"specifies what to save for :mkview",
	"use .viminfo file upon startup and exiting",
	"when to use virtual editing",
	"use visual bell instead of beeping",
	"warn for shell command when buffer was changed",
	"for terminals that have weird inversion method",
	"allow specified keys to cross line boundaries",
	"command-line character for wildcard expansion",
	"like 'wildchar",
	"files matching these patterns are not completed",
	"ignore case when completing file names",
	"use menu for command line completion",
	"mode for 'wildchar",
	"specifies how command line completion is done",
	"when the windows system handles ALT keys",
	"nr of lines to scroll for CTRL-F and CTRL-B",
	"minimum number of lines for the current window",
	"keep window height when opening/closing windows",
	"keep window width when opening/closing windows",
	"minimum number of lines for any window",
	"minimal number of columns for any window",
	"minimal number of columns for current window",
	"long lines wrap and continue on the next line",
	"chars from the right where wrapping starts",
	"searches wrap around the end of the file",
	"writing to a file is allowed",
	"write to file with no need for '!' override",
	"make a backup before overwriting a file",
	"delay this many msec for each char (for debug)",
}
